name: StireAnniversary
version: '${project.version}'
main: nl.raspen0.stireanniversary.StireAnniversary
api-version: 1.17
authors: [ raspen0 ]
description: Plugin that manages the features for the 10th anniversary of Stirebuild.
softdepend:
  - Essentials
  - StireTweaks
commands:
  sa_home:
    description: Teleports player to their base in the current anniversary world.
    usage: /sa_home
  sa_teleport:
    description: Teleports the target player to the given base.
    usage: /sa_teleport <base name / base ID> <target>
  sa_import:
    description: Imports base data from other plugins.
    usage: /sa_import
  sa_reload:
    description: Reloads data of the plugin.
    usage: /sa_reload
  sa_spawn:
    description: Returns the sender to the spawn location of the current Anniversary world.
    usage: /sa_reload
  island:
    description: Replacement command for the original IslandWorld command.
    usage: /island
  survey:
    description: Replacement command for the original BetterAlias command.
    usage: /survey
  enmessage:
    description: Replacement command for the original BetterAlias command.
    aliases: ["nlmessage"]
    usage: /enmessage
  ar:
    description: Replacement command for the original AutoRank command.
    usage: /ar
  calladmin:
    description: Replacement command for the original JSONAPI command.
    usage: /calladmin
  pa:
    description: Replacement command for the original PvPArena command.
    usage: /pa
  shop:
    description: Replacement command for the original BossShop command.
    usage: /shop